language: node_js
node_js:
  - "node"
before_script:
  - git config --global user.name "HsuTing"
script:
  - yarn lint
  - yarn build
  - yarn prod
  - yarn test
branches:
only:
  - master
cache:
yarn: true
